### ISSUE TITLE
node 12 error

### ISSUE THREAD

**Issue by unwriter** [interplanaria/bitwork#4]
When running on node12, the error below is thrown.

It doesn't happen on node10.

```
/root/bitworktest/node_modules/b2p2p/lib/messages/index.js:101
    throw new Error('Unsupported message command: ' + command);
    ^

Error: Unsupported message command: protoconf
    at Messages._buildFromBuffer (/root/bitworktest/node_modules/b2p2p/lib/messages/index.js:101:11)
    at Messages.parseBuffer (/root/bitworktest/node_modules/b2p2p/lib/messages/index.js:74:15)
    at Peer._readMessage (/root/bitworktest/node_modules/b2p2p/lib/peer.js:219:31)
    at Peer._readMessage (/root/bitworktest/node_modules/b2p2p/lib/peer.js:222:10)
    at Peer._readMessage (/root/bitworktest/node_modules/b2p2p/lib/peer.js:222:10)
    at Socket.<anonymous> (/root/bitworktest/node_modules/b2p2p/lib/peer.js:167:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
```

**Comment by unwriter** [comment]
Turns out this is not an error with node version, but the new bitcoin node implementation `0.2.2.beta` is broken. 

https://download.bitcoinsv.io/bitcoinsv/0.2.2.beta/

"Downgrading" to 0.2.1 fixed this.

**Comment by jerrygzy** [comment]
I got this error with 1.0.0 genesis stable release
error msg:
```
owaf@jet:~/work/planaria$ node index
/home/owaf/node_modules/_b2p2p@0.0.1@b2p2p/lib/messages/index.js:101
    throw new Error('Unsupported message command: ' + command);
    ^

Error: Unsupported message command: protoconf
    at Messages._buildFromBuffer (/home/owaf/node_modules/_b2p2p@0.0.1@b2p2p/lib/messages/index.js:101:11)
    at Messages.parseBuffer (/home/owaf/node_modules/_b2p2p@0.0.1@b2p2p/lib/messages/index.js:74:15)
    at Peer._readMessage (/home/owaf/node_modules/_b2p2p@0.0.1@b2p2p/lib/peer.js:219:31)
    at Peer._readMessage (/home/owaf/node_modules/_b2p2p@0.0.1@b2p2p/lib/peer.js:222:10)
    at Peer._readMessage (/home/owaf/node_modules/_b2p2p@0.0.1@b2p2p/lib/peer.js:222:10)
    at Socket.<anonymous> (/home/owaf/node_modules/_b2p2p@0.0.1@b2p2p/lib/peer.js:167:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
```

**Comment by jerrygzy** [comment]
Bitcoin SV node version
```
root@d57fef:/# bitcoind -version
Bitcoin SV version v1.0.0.0
Copyright (C) 2009-2020 The Bitcoin Association

Please contribute if you find Bitcoin SV useful. Visit <https://bitcoinsv.io>
for further information about the software.
The source code is available from <https://github.com/bitcoin-sv/bitcoin-sv>.

This is experimental software.
Distributed under the Open BSV software license, see the accompanying file
LICENSE

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org> and cryptographic software written by
Eric Young and UPnP software written by Thomas Bernard.
```

**Comment by binde-io** [comment]
It seems that BitcoinSV node is not compatible with the current version of b2p2p.  deanmlittle has forked b2p2p to https://github.com/deanmlittle/bsv-p2p and it looks that it is compatible with BitcoinSV node 1.0.0.
I have installed it under bitwork node-modules, updated the reference from b2p2p to bsv-p2p and it seems to have fixed the error message.
I have not made a thorough review of bsv-p2p.

**Comment by binde-io** [comment]
Tested bitwork with node version 1.0.1 and it still throws the "Unsupported message command: protoconf" error.
bsv-p2p seems to be working fine in bitwork using node 1.0.1.

**Comment by unwriter** [comment]
Fixed with https://github.com/interplanaria/bitwork/commit/4231992d36757e34881487d9e1b2ba4a16fb00c2
